### ISSUE TITLE
[Documentation] Contributing to the Project

### ISSUE THREAD

**Issue by Dourin** [Dourin/CompreC#19]
## Proposed changes

This issue aims to create a contributing file that provides guidelines for contributing to the project. The focus is on helping potential contributors understand the process of reporting issues, submitting pull requests, and following development practices.

## Description

The contributing file serves as a guide for anyone interested in contributing to the project. It outlines the steps to report bugs, request features, ask questions, and submit pull requests. The file also emphasizes the importance of adhering to style guidelines, maintaining code quality, and providing clear test instructions.

## Types of changes

This issue introduces a documentation update to add the contributing file.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation Update (if none of the other choices apply)

## Further comments

By providing clear guidelines for contributing, this project aims to foster collaboration and encourage community involvement. It is important to maintain an open and inclusive environment, welcoming contributions from all levels of expertise.

Additionally, this contributing file will serve as a reference for contributors, ensuring a streamlined and efficient process for reporting issues and submitting pull requests.

Let's create a contributing file that promotes a positive and constructive contribution culture for the project.

**Comment by thibaultleguern** [comment]
This closes #43
