### ISSUE TITLE
[Documentation] Update README.md

### ISSUE THREAD

**Issue by Dourin** [Dourin/CompreC#21]
## Proposed changes

This pull request aims to update the README.md file for the CompreC project. The README provides essential information about the project, its features, installation instructions, usage examples, contribution guidelines, license information, and authors.

The changes made to the README.md file include:

- Updated project description and purpose
- Installation instructions with steps for cloning the repository, navigating to the project directory, and compiling the source code using the `make` command
- Usage section explaining the available command-line options and their functionalities
- Examples of how to use CompreC with different options
- Contribution guidelines directing potential contributors to the CONTRIBUTING.md file for instructions
- License information stating that CompreC is an open-source project released under an [ESGI](https://www.esgi.fr) school project
- Authors section listing the contributors and providing links to their respective profiles

These updates provide clear and concise information for users, making it easier for them to understand and utilize the features of CompreC.

## Types of changes

- [ ] Bugfix
- [ ] New feature
- [x] Documentation Update

## Further comments

By updating the README.md file, we improve the overall user experience by providing detailed instructions for installation, usage, and contribution. This will help new users get started with the project and facilitate their understanding of its features.

The README.md file plays a crucial role in introducing the project and attracting potential contributors. With the updated content, users will have a comprehensive overview of the project, its capabilities, and how they can actively participate in its development.

This documentation update falls under the category of "Documentation" as it enhances the project's documentation to provide a better understanding of its usage, installation, and contribution processes.

**Comment by SrNightmare09** [comment]
Hey @Dourin! I think I can contribute towards the documentation aspect of this project. Let me know what you think!

**Comment by Dourin** [comment]
Hey  @SrNightmare09 ! Thank you so much for offering to contribute to the documentation aspect of this project. I truly appreciate your willingness to help.

However, this project is currently a school project, and we have limitations on external contributions at this time. But I want to express my gratitude for your enthusiasm and interest in collaborating with us.

If you're still interested in contributing, I would be more than happy to consider your involvement starting from Monday, July 24, 2023. Please let me know if you'd like to proceed, and we can discuss further details.

Once again, thank you for your understanding and support <3

**Comment by SrNightmare09** [comment]
@Dourin Definitely! I will be more than happy to contribute to this project, and I do not mind the waiting.
